name: Rollback yum update
on:
  workflow_dispatch:
    inputs:
      host:
        description: 'IP address of the VM'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and rollback
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.host }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Connecting to host ${{ inputs.host }}..."
            sudo yum history list | awk '/^ *[0-9]/ {print $1}' | head -1 > /tmp/yum-history
            yum_history=$(cat /tmp/yum-history)
            echo "Rolling back last yum update ($yum_history) on ${{ inputs.host }}..."
            expect -c 'spawn ssh $env(USERNAME)@$env(HOST) "sudo yum history undo -y $env(yum_history)"; expect "*?assword:*"; send -- "$env(PASSWORD)\r"; interact;'
      - name: Reboot VM
        uses: appleboy/ssh-action@master
        if: always()
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Rebooting host ${{ matrix.host }}..."
            sudo yum install -y expect
            expect -c 'spawn ssh $env(USERNAME)@$env(HOST) sudo reboot; expect "*?assword:*"; send -- "$env(PASSWORD)\r"; interact;'
      
      - name: Wait for VM to come back
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo yum install -y nc
            echo "Waiting for host ${{ matrix.host }} to come back..."
            until nc -z -v -w5 ${{ matrix.host }} 22; do sleep 5; done
            echo "Success: Host ${{ matrix.host }} is back up and running"
